const { build } = require("esbuild");

build({
	entryPoints: ["src/index.ts"],
	outfile: "dist/index.js",
	platform: "node",
	format: "cjs",
	bundle: true,
	sourcemap: true,
	target: "node18",
	external: [
		"electron",
		"sharp",
		"node-vibrant",
		"ffmpeg-static",
		"ffprobe-static",
		"ngrok",
		"p-limit",
		"pino",
		"pino-pretty",
		"properties-reader",
		"swagger-ui-express",
		"tsoa",
		"ws",
		"bcrypt",
		"cheerio",
		"cookie-parser",
		"cors",
		"dotenv",
		"express",
		"express-rate-limit",
		"follow-redirects",
		"fs-extra",
		"helmet",
		"jsonwebtoken",
		"moviedb-promise",
		"multer",
		"reflect-metadata",
		"uuid",
		"axios",
		"better-sqlite3",
	],
}).catch(() => process.exit(1));
