/** @type {import('jest').Config} */
const uuidShim = "<rootDir>/src/__tests__/helpers/uuid-shim.cjs";
const cliShim = "<rootDir>/src/__tests__/helpers/cli-shim.cjs";
const electronShim = "<rootDir>/src/__tests__/helpers/electron-shim.cjs";

const sharedTransform = {
	"^.+\\.ts$": "ts-jest",
};

const sharedModuleNameMapper = {
	"^uuid$": uuidShim,
	"^@seerial/cli$": cliShim,
	"^electron$": electronShim,
	"^@/index$": "<rootDir>/src/__tests__/helpers/index-shim.cjs",
	"^@/(.*)$": "<rootDir>/src/$1",
	"^(\\.{1,2}/.*)\\.js$": "$1",
};

module.exports = {
	preset: "ts-jest",
	testEnvironment: "node",
	roots: ["<rootDir>/src"],
	testMatch: ["**/__tests__/**/*.test.ts", "**/?(*.)+(spec|test).ts"],
	transform: sharedTransform,
	collectCoverageFrom: [
		"src/**/*.ts",
		"!src/**/*.d.ts",
		"!src/**/__tests__/**",
		"!src/index.ts",
		"!src/routes/routes.ts",
		"!src/api/v1/shared/infrastructure/adapters/di/container.ts",
		"!src/utils/appTray.ts",
		"!src/utils/publish.ts",
		"!src/api/v1/shared/infrastructure/adapters/metadata/MetadataProviderImpl.ts",
		"!src/api/v1/shared/infrastructure/adapters/metadata/TMDbApiClient.ts",
		"!src/api/v1/shared/infrastructure/adapters/imdb-score/IMDBScoreServiceImpl.ts",
		"!src/api/v1/shared/infrastructure/services/FileSearchService.ts",
		"!src/api/v1/shared/infrastructure/services/MediaService.ts",
		"!src/api/v1/shared/infrastructure/services/MediaDetailsService.ts",
		"!src/api/v1/shared/infrastructure/services/MusicBrainzService.ts",
		"!src/api/v1/shared/infrastructure/services/ExternalSearchService.ts",
		"!src/api/v1/shared/infrastructure/services/ConfigService.ts",
		"!src/api/v1/servers/infrastructure/services/ServerConfigService.ts",
		"!src/api/v1/shared/infrastructure/adapters/filesystem/FileSystemServiceImpl.ts",
		"!src/api/v1/shared/infrastructure/adapters/image-processing/ImageProcessingServiceImpl.ts",
		"!src/api/v1/videos/infrastructure/services/VideoProcessingServiceImpl.ts",
		"!src/api/v1/videos/infrastructure/services/VideoExtractionServiceImpl.ts",
		"!src/api/v1/libraries/application/services/LibraryManager.ts",
		"!src/api/v1/libraries/application/usecases/ScanLibraryUseCase.ts",
		"!src/api/v1/movies/application/usecases/ScanMovieUseCase.ts",
		"!src/api/v1/movies/application/usecases/RefreshMovieMetadataUseCase.ts",
		"!src/api/v1/movies/application/usecases/UpdateMovieMetadataUseCase.ts",
		"!src/api/v1/series/application/usecases/ScanSeriesUseCase.ts",
		"!src/api/v1/series/application/usecases/RefreshMetadataUseCase.ts",
		"!src/api/v1/songs/application/usecases/ScanSongsUseCase.ts",
		"!src/api/v1/songs/infrastructure/services/AudioProcessingServiceImpl.ts",
		"!src/api/v1/seasons/application/usecases/DeleteSeasonDataUseCase.ts",
		"!src/api/v1/movies/application/usecases/DeleteMovieDataUseCase.ts",
		"!src/api/v1/series/application/usecases/DeleteSeriesDataUseCase.ts",
		"!src/api/v1/series/application/usecases/ProcessEpisodeUseCase.ts",
		"!src/api/v1/series/application/usecases/UpdateSeriesMetadataUseCase.ts",
		"!src/api/v1/series/application/usecases/UpdateEpisodeGroupUseCase.ts",
		"!src/api/v1/series/application/usecases/UpdateShowIdUseCase.ts",
		"!src/api/v1/watch-lists/infrastructure/persistence/repositories/WatchListRepositoryImpl.ts",
		"!src/api/v1/libraries/infrastructure/persistence/repositories/LibrariesRepositoryImpl.ts",
		"!src/helpers/RelationshipCreationHelper.ts",
		"!src/middleware/audio.middleware.ts",
		"!src/utils/utils.ts",
	],
	coverageThreshold: {
		global: {
			lines: 60,
			branches: 50,
		},
	},
	setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
	testTimeout: 30000,
	moduleNameMapper: sharedModuleNameMapper,
	projects: [
		{
			displayName: "unit",
			preset: "ts-jest",
			testEnvironment: "node",
			testMatch: ["<rootDir>/src/__tests__/unit/**/*.test.ts"],
			transform: sharedTransform,
			setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
			moduleNameMapper: sharedModuleNameMapper,
			testTimeout: 10000,
		},
		{
			displayName: "integration",
			preset: "ts-jest",
			testEnvironment: "node",
			testMatch: ["<rootDir>/src/__tests__/integration/**/*.test.ts"],
			transform: sharedTransform,
			setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
			moduleNameMapper: sharedModuleNameMapper,
			testTimeout: 30000,
		},
		{
			displayName: "live",
			preset: "ts-jest",
			testEnvironment: "node",
			testMatch: ["<rootDir>/src/__tests__/live/**/*.test.ts"],
			transform: sharedTransform,
			setupFilesAfterEnv: ["<rootDir>/src/__tests__/setup.ts"],
			moduleNameMapper: sharedModuleNameMapper,
			testTimeout: 60000,
		},
	],
};
