export const NavigationFocusKeys = {
	topBar: {
		container: "topBar",
		home: "home",
		movies: "movies",
		shows: "shows",
		music: "music",
		toSee: "toSee",
		musicPlayer: "music-player",
		settings: "settings",
	},
	libraryContent: {
		container: "libraryContent",
	},
	details: {
		container: "details",
		playButton: "details-play-button",
		playFromStartButton: "details-play-from-start-button",
		markWatchedButton: "details-mark-watched-button",
		optionsButton: "details-options-button",
		goBackButton: "details-go-back-button",
	},
	music: {
		shuffle: "music-shuffle",
		repeat: "music-repeat",
	},
	player: {
		container: "player",
		timeline: "player-timeline",
		playPauseButton: "player-play-pause-button",
		rewindButton: "player-rewind-button",
		forwardButton: "player-forward-button",
		karaokeButton: "player-karaoke-button",
		karaokeSlider: "player-karaoke-slider",
		lyricsButton: "player-lyrics-button",
		lyricsOptionsButton: "player-lyrics-options-button",
		volumeButton: "player-volume-button",
		videoTracksButton: "player-video-tracks-button",
		audioTracksButton: "player-audio-tracks-button",
		subtitleTracksButton: "player-subtitle-tracks-button",
		settingsButton: "player-settings-button",
		optionsButton: "player-options-button",
		goBackButton: "player-go-back-button",
		openQueueButton: "player-open-queue-button",
		closeButton: "player-close-button",
		repeatButton: "player-repeat-button",
		shuffleButton: "player-shuffle-button",
		chapters: "player-chapters",
	},
	settings: {
		container: "settings-panel",
	},
};
