name: Build and Publish (Win, MacOS, Linux)

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build-win
      - run: npx electron-builder --win --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build-mac
      - run: npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build-linux
      - run: npx electron-builder --linux --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
